name: Build

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - 'main'

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true

defaults:
  run:
    shell: pwsh

jobs:
  lint_csharp:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      
    - name: Install dotnet format
      run: dotnet tool update -g dotnet-format
      
    - name: Run dotnet format
      run: dotnet format --check -v:normal

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1

    - name: Build
      run: dotnet build --configuration Release

    - name: Test
      run: dotnet test --configuration Release
